### ISSUE TITLE
Use deb instead of wrapper

### ISSUE THREAD

**Issue by jaywink** [jaywink/ansible-letsencrypt#1]
Consider using the debs from Xenial (https://iliketoast.net/posts/874468)

**Comment by jaywink** [comment]
It seems Certbot never made it to Xenial, but there is a PPA: https://launchpad.net/%7Eondrej/+archive/ubuntu/letsencrypt

This could be conditionally used if on Xenial.

**Comment by gronke** [comment]
Could be deprecated with merging #17 through replacing certbot with simp_le.

**Comment by jaywink** [comment]
I'll close this right away anyway, no point trying to use a package for only some certain version - better keep it simple :)
